name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C compiler
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Compile moon phase program
        run: |
          gcc -o build/moon src/main.c

      - name: Generate checksums
        run: |
          shasum -a 256 build/* > build/checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/moon
            build/checksums.txt

